# Generated by Django 5.1.7 on 2025-04-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0003_attendancesession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancesession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session')},
        ),
    ]
