# Generated by Django 5.1.7 on 2025-04-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_session_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
