# Generated by Django 5.1.7 on 2025-04-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_ended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='start_time',
        ),
    ]
